In [1]:
import numpy as np #Array constructor from numpy module

In [2]:
a=np.array([1,2,3,4,5]) #modulename.functionname(np.array)
print(a)

[1 2 3 4 5]


In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a[0])

1


Properties of Numpy Array

1.Shape(.shape)

2.ndim(.ndim) gives dimension of array

3.dtype(.dtype) gives data type of array

4.size(.size) gives you the total number of elements in array.

5.itemsize(.itemsize) gives you memory allocated to each element.

In [6]:
print("The shape of 1D Array is: ",a.shape)
print("The shape of 2D array is :",b.shape)

The shape of 1D Array is:  (5,)
The shape of 2D array is : (3, 3)


In [7]:
print("The dimension of 1D Array is: ",a.ndim)
print("The dimension of 2D Array is: ",b.ndim)

The dimension of 1D Array is:  1
The dimension of 2D Array is:  2


In [8]:
print("The datatype of a array: ",a.dtype)
print("The datatype of b array: ",b.dtype)

The datatype of a array:  int64
The datatype of b array:  int64


In [9]:
print("The total number of elements i.e. size if array a is: ",a.size)
print("The total number of elements i.e. size if array b is: ",b.size)

The total number of elements i.e. size if array a is:  5
The total number of elements i.e. size if array b is:  9


In [10]:
print("Itemsize of elements in array a: ",a.itemsize)
print("Itemsize of elements in array b: ",b.itemsize)

Itemsize of elements in array a:  8
Itemsize of elements in array b:  8


In [11]:
p=np.array([1,2,3],float)
p

array([1., 2., 3.])

In [12]:
p.tolist()
p

array([1., 2., 3.])

In [13]:
list(p)

[1.0, 2.0, 3.0]

In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
d=range(1,3,-2)
print(d)

range(1, 3, -2)


In [16]:
set(range(1,3,-2))

set()

In [17]:
range(1,3)

range(1, 3)

In [18]:
print(range)

<class 'range'>
